version: '3.1'

# MongoDB, Postgres, Redis, Elasticsearch, Kibana, Mysql, etc
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root