### Get Rider Coordinates
GET http://localhost:3002/rider-coordinates

### POST Rider Coordinates
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
    # "lat": 1233.23,
    "lng": 123123123.23,
    "rider": "dffds32432423423423423433er"
}